# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency_converter.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'currency_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63urrency_converter.proto\"L\n\x0e\x43onvertRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"+\n\x0f\x43onvertResponse\x12\x18\n\x10\x63onverted_amount\x18\x01 \x01(\x01\x32\x41\n\x11\x43urrencyConverter\x12,\n\x07\x43onvert\x12\x0f.ConvertRequest\x1a\x10.ConvertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=28
  _globals['_CONVERTREQUEST']._serialized_end=104
  _globals['_CONVERTRESPONSE']._serialized_start=106
  _globals['_CONVERTRESPONSE']._serialized_end=149
  _globals['_CURRENCYCONVERTER']._serialized_start=151
  _globals['_CURRENCYCONVERTER']._serialized_end=216
# @@protoc_insertion_point(module_scope)
